### ISSUE TITLE
Attempts variable with while loop

### ISSUE THREAD

**Issue by Zardrian** [Zardrian/Learning-Projects---PYTHON#1]
Not working as intended, don't know why, need help. The base random number guess works just dandy

**Comment by floh1695** [comment]
What part of the code is there an issue?

What is the code supposed to do?

**Comment by Zardrian** [comment]
the user is suppposed to be prompted to put in how many times they want to try to guess, then the game is supposed to shut them down when they get to that point (ie: 1 guess = 1 try). But the counter gives one too many, and the end there's supposed to be a message saying something like "You took too many guesses" when it fails, but that never happens. Basically i think i messed up the counter in the loop somewhat but cant find out whats up

**Comment by Zardrian** [comment]
Either you did something or I just fixed it
